#DGLAB-OI配置文件
#蒟蒻杂鱼是会被电电的哦~欸嘿~
#Design By MossCG

#前言
#请在测试好自己抗电能力之后再修改配置文件哦~
#电坏了咱不负责哦~
#当你确认配置没问题后，请将以下选项修改为true后再启动客户端喵
enable: false

#----------------------------------
#以下为强度设置
#强度将会自动舍取为int值并同步到郊狼
#记得注意上下限哦~
#最最最下面有建议参考数值哦~

#强度上限
#if (value>limit) v=limit;
limit: 100.0

#基础强度
basicValue: 1.0

#WA/TLE/MLE增量
#不会有杂鱼会WA十几发吧~
#value+=WATimes*WAValue
WAValue: 1.0

#AC增量
#杂鱼~AC有奖励哦~
#value+=ACTimes*ACValue
ACValue: -10.0

#排名强度
#如果打的是校赛/周赛这种人少的小比赛，可以设置为1.0上下
#如果打的是CF一类的大比赛，建议设置为0.01左右
#自己算一下啊喂！别把自己电坏了！！！
#value+=(rank-1)*rankValue
rankValue: 1.0

#强度设置就到这里了哦~

#----------------------------------
#是否显示调试信息
debug: false

#----------------------------------
#数值建议/参考上限100

#校赛/周赛，人数<100
#limit: 100.0
#basicValue: 10.0
#WAValue: 5.0
#ACValue: -10.0
#rankValue: 1.0

#Codeforces，人数>10000，预估排名<10000
#limit: 100.0
#basicValue: 10.0
#WAValue: 2.0
#ACValue: -5.0
#rankValue: 0.01
